#!/usr/bin/env bash

xidlehook \
  --not-when-fullscreen \
  --not-when-audio \
  --timer 300 \
    'xrandr --output eDP1 --brightness .5' \
    'xrandr --output eDP1 --brightness 1' \
  --timer 600 \
    'xrandr --output eDP1 --brightness 1; betterlockscreen -l dimblur' \
    ''\
  --timer 1200 \
    'systemctl suspend' \
    ''
